[book]
authors = ["Yaossg"]
language = "zh-Hans"
multilingual = false
src = "src"
title = "Biome"

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
git-repository-url = "https://github.com/Yaossg/biome"
site-url = "/biome/"

[output.linkcheck]